name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  chromaui:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: npm ci
      #👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
        id: chromatic
      - name: Update GitHub About Link
        run: |
          STORYBOOK_URL="${{ steps.chromatic.outputs.storybookUrl }}"
          echo "Updating GitHub About section with Storybook URL: $STORYBOOK_URL"
          
          GITHUB_API="https://api.github.com/repos/${{github.repository_owner}}${{ github.repository }}"
          echo "GITHUB_API: $GITHUB_API"

          # Update the repository about link
          curl -X PATCH $GITHUB_API \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "{\"description\": \"Latest Storybook: $STORYBOOK_URL\"}"
          -d '{"homepage": "[Demo Page]($STORYBOOK_URL)"}'